# Generated by Django 2.2.5 on 2019-09-26 20:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='intro',
        ),
        migrations.AlterField(
            model_name='bio',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
