# Generated by Django 2.2.5 on 2019-09-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('other_pages', '0003_gallerypage_gallerypagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
