# Generated by Django 2.2.5 on 2020-02-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0007_gallerypagegalleryimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypagegalleryimage',
            name='title',
        ),
    ]
