# Generated by Django 2.2.5 on 2020-02-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0009_gallerypagegalleryimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
    ]
